### ISSUE TITLE
Handle Channel-close events that are not triggered by the underlying connection

### ISSUE THREAD

**Issue by denic** [OpusCapita/event-client#12]
Channel close events can happen on malformed commands send to the broker (or by closing the channel by killing the erlang process handling the channel). In that case the AmqpChannel class needs to handle the re-initialization of the amqp-lib channel on its own.

references OpusCapita/businessnetwork#195

**Comment by maciej-wakula-opuscapita** [comment]
Channel is more often closed when node thread gets locked for the heartbeat+timeout duration (12s-15s in our case). Then RabbitMQ considers connection to be dead and disconnects.
Also new version of RabbitMQ is very different from the one that was used in the past.
The re-connect feature is already there (though failing in some difficult to reproduce conditions).
Closing for now as we already have re-connect feature, know one important cause for connection failures and are unable to identify any other scenarios in which an implementation can be provided.
